name: Release - Create Release Task in Asana

on:
  workflow_dispatch:
    inputs:
      app-version:
        description: 'App Version for Release'
        required: true
        default: 'PLACEHOLDER'

env:
  ASANA_PAT: ${{ secrets.GH_ASANA_SECRET }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create_release_task:
    name: Create Android App Release Task in Asana
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check app-version value
        run: |
          if [ "${{ github.event.inputs.app-version }}" == "PLACEHOLDER" ]; then
            echo "Input value cannot be 'PLACEHOLDER'."
            exit 1
          else
            echo "Input value is valid: ${{ github.event.inputs.app-version }}"
          fi

      - name: Install Release Bridge from Homebrew
        run: |
          brew tap cdrussell/aarb
          brew install aarb

      - name: Create task in Asana
        run: |
          AndroidAsanaBridge version=${{ github.event.inputs.app-version }} action=createRelease,tagPendingTasks,addLinksToDescription,removePendingTasks board=fake

      - name: Assign task to Github Actor
        id: assign-release-task
        uses: ./.github/actions/assign-release-task
        with:
          task_name: 'Android Release ${{ github.event.inputs.app-version }}'
          asana_token: ${{ secrets.GH_ASANA_SECRET }}
          project_gid: "1200415422192046"
          username: ${{ github.actor }}

